# Data Cleaning Workflow

In [ ]:
import pandas as pd

# Load the dataset
file_path = '/content/drive/MyDrive/Colab Notebooks/Dataset for Data Analytics.xlsx'
df = pd.read_excel(file_path)

print('Original DataFrame Head:')
display(df.head())
print('\nOriginal DataFrame Info:')
df.info()
print('\nOriginal Missing values:')
display(df.isnull().sum())

Original DataFrame Head:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

Original DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

Original Missing values:

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

## Handling Missing Values

Based on the initial inspection, only the `coupon_code` column has missing values. We have two primary approaches for handling these:

1.  **Filling missing values**: Replacing `NaN` values with a suitable substitute (e.g., a default string like 'No Coupon', the mean/median for numerical data, or the mode for categorical data). This approach helps retain the rows and thus, more data.
2.  **Removing rows with missing values**: Dropping rows that contain `NaN` values. This is suitable when the number of missing values is small, or when the missingness is critical and cannot be accurately imputed.

For `coupon_code`, we will **fill** the missing values with 'No Coupon' to avoid losing approximately 25% of our data, as dropping rows for this particular column might not be the most appropriate strategy for data retention.

In [ ]:
# Create a copy to avoid SettingWithCopyWarning later if 'df' is used elsewhere
df_cleaned = df.copy()

# Fill missing values in 'CouponCode' with 'No Coupon'
df_cleaned['CouponCode'] = df_cleaned['CouponCode'].fillna('No Coupon')

print('\nMissing values after filling NaNs in CouponCode:')
display(df_cleaned.isnull().sum())

Missing values after filling NaNs in CouponCode:

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

## Removing Duplicates

Now, let's identify and remove any duplicate rows to ensure data uniqueness.

In [ ]:
initial_rows = df_cleaned.shape[0]
df_cleaned.drop_duplicates(inplace=True)
duplicate_rows_removed = initial_rows - df_cleaned.shape[0]

print(f"\nNumber of duplicate rows removed: {duplicate_rows_removed}")
print(f"DataFrame shape after removing duplicates: {df_cleaned.shape}")

Number of duplicate rows removed: 0
DataFrame shape after removing duplicates: (1200, 14)

## Correcting Data Formats

This step involves standardizing column names (lowercase, replace spaces with underscores) and ensuring data types are appropriate for analysis. Based on `df.info()`, `Date` is already datetime, and there's no `Age` column to convert.

In [ ]:
# Standardize column names
df_cleaned.columns = df_cleaned.columns.str.lower().str.replace(' ', '_')

# Convert 'date' column to datetime objects (though it might already be)
df_cleaned['date'] = pd.to_datetime(df_cleaned['date'], errors='coerce')

print('\nStandardized Column Names:')
print(df_cleaned.columns)

print('\nDataFrame Info after data type correction:')
df_cleaned.info()

print('\nMissing values after type conversion (should be 0):')
display(df_cleaned.isnull().sum())

print('\nCleaned DataFrame Head:')
display(df_cleaned.head())

Standardized Column Names:
Index(['orderid', 'date', 'customerid', 'product', 'quantity', 'unitprice',
       'shippingaddress', 'paymentmethod', 'orderstatus', 'trackingnumber',
       'itemsincart', 'couponcode', 'referralsource', 'totalprice'],
      dtype='object')

DataFrame Info after data type correction:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   orderid          1200 non-null   object
 1   date             1200 non-null   datetime64[ns]
 2   customerid       1200 non-null   object
 3   product          1200 non-null   object
 4   quantity         1200 non-null   int64
 5   unitprice        1200 non-null   float64
 6   shippingaddress  1200 non-null   object
 7   paymentmethod    1200 non-null   object
 8   orderstatus      1200 non-null   object
 9   trackingnumber   1200 non-null   object
 10  itemsincart      1200 non-null   int64
 11  couponcode       1200 non-null   object
 12  referralsource   1200 non-null   object
 13  totalprice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

Missing values after type conversion (should be 0):

orderid            0
date               0
customerid         0
product            0
quantity           0
unitprice          0
shippingaddress    0
paymentmethod      0
orderstatus        0
trackingnumber     0
itemsincart        0
couponcode         0
referralsource     0
totalprice         0
dtype: int64

Cleaned DataFrame Head:

,orderid,date,customerid,product,quantity,unitprice,shippingaddress,paymentmethod,orderstatus,trackingnumber,itemsincart,couponcode,referralsource,totalprice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

## Download Cleaned Dataset

You can download the cleaned dataset as a CSV file using the following cell.

In [ ]:
from google.colab import files

output_file_name = 'cleaned_dataset.csv'
df_cleaned.to_csv(output_file_name, index=False)

print(f"Cleaned dataset saved as '{output_file_name}'")
files.download(output_file_name)

Cleaned dataset saved as 'cleaned_dataset.csv'